/// Allohning 99 go'zal ismi (Asmaul Husna).
/// [arabic] — arabcha yozuv, [latin] — o'zbekcha talaffuz, [meaning] — ma'nosi.
class AsmaName {
  final int number;
  final String arabic;
  final String latin;
  final String meaning;

  const AsmaName(this.number, this.arabic, this.latin, this.meaning);
}

const List<AsmaName> asmaulHusna = [
  AsmaName(1, 'الرحمن', 'Ar-Rahmon', 'Cheksiz mehribon'),
  AsmaName(2, 'الرحيم', 'Ar-Rahiym', 'Qiyomatda rahm qiluvchi'),
  AsmaName(3, 'الملك', 'Al-Malik', 'Butun borliq egasi, Podshoh'),
  AsmaName(4, 'القدوس', 'Al-Quddus', 'Har qanday nuqsondan pok'),
  AsmaName(5, 'السلام', 'As-Salom', 'Salomatlik va tinchlik beruvchi'),
  AsmaName(6, 'المؤمن', 'Al-Mu\'min', 'Omonlik beruvchi, ishonchli'),
  AsmaName(7, 'المهيمن', 'Al-Muhaymin', 'Hamma narsani nazorat qiluvchi'),
  AsmaName(8, 'العزيز', 'Al-Aziyz', 'Yengilmas qudrat egasi'),
  AsmaName(9, 'الجبار', 'Al-Jabbor', 'Irodasini o\'tkazuvchi, islohot qiluvchi'),
  AsmaName(10, 'المتكبر', 'Al-Mutakabbir', 'Ulug\'lik va kibriyo egasi'),
  AsmaName(11, 'الخالق', 'Al-Xoliq', 'Yaratuvchi'),
  AsmaName(12, 'البارئ', 'Al-Bori\'', 'Yo\'qdan bor qiluvchi'),
  AsmaName(13, 'المصور', 'Al-Musavvir', 'Suvrat, shakl beruvchi'),
  AsmaName(14, 'الغفار', 'Al-G\'affor', 'Gunohlarni ko\'p kechiruvchi'),
  AsmaName(15, 'القهار', 'Al-Qahhor', 'Har narsadan g\'olib, qahri qattiq'),
  AsmaName(16, 'الوهاب', 'Al-Vahhob', 'Behisob in\'om beruvchi'),
  AsmaName(17, 'الرزاق', 'Ar-Razzoq', 'Rizq beruvchi'),
  AsmaName(18, 'الفتاح', 'Al-Fattoh', 'Yaxshilik eshiklarini ochuvchi'),
  AsmaName(19, 'العليم', 'Al-Aliym', 'Hamma narsani biluvchi'),
  AsmaName(20, 'القابض', 'Al-Qobiz', 'Rizqni siquvchi, jonni oluvchi'),
  AsmaName(21, 'الباسط', 'Al-Bosit', 'Rizqni keng qiluvchi'),
  AsmaName(22, 'الخافض', 'Al-Xofiz', 'Pastga tushiruvchi'),
  AsmaName(23, 'الرافع', 'Ar-Rofi\'', 'Yuksaltiruvchi'),
  AsmaName(24, 'المعز', 'Al-Mu\'izz', 'Izzat, sharaf beruvchi'),
  AsmaName(25, 'المذل', 'Al-Muzill', 'Xor qiluvchi'),
  AsmaName(26, 'السميع', 'As-Samiy\'', 'Hamma narsani eshituvchi'),
  AsmaName(27, 'البصير', 'Al-Basiyr', 'Hamma narsani ko\'ruvchi'),
  AsmaName(28, 'الحكم', 'Al-Hakam', 'Hukm chiqaruvchi, hakam'),
  AsmaName(29, 'العدل', 'Al-Adl', 'Cheksiz adolatli'),
  AsmaName(30, 'اللطيف', 'Al-Latiyf', 'Marhamatli, nozik ish tutuvchi'),
  AsmaName(31, 'الخبير', 'Al-Xabiyr', 'Hamma narsadan xabardor'),
  AsmaName(32, 'الحليم', 'Al-Haliym', 'Halim, jazoda shoshilmaydigan'),
  AsmaName(33, 'العظيم', 'Al-Aziym', 'Buyuk, ulug\''),
  AsmaName(34, 'الغفور', 'Al-G\'afur', 'Mag\'firat qiluvchi'),
  AsmaName(35, 'الشكور', 'Ash-Shakur', 'Oz amalga ko\'p mukofot beruvchi'),
  AsmaName(36, 'العلي', 'Al-Aliyy', 'Eng oliy, yuksak'),
  AsmaName(37, 'الكبير', 'Al-Kabiyr', 'Eng ulug\''),
  AsmaName(38, 'الحفيظ', 'Al-Hafiyz', 'Saqlovchi, muhofaza qiluvchi'),
  AsmaName(39, 'المقيت', 'Al-Muqiyt', 'Rizq va quvvat beruvchi'),
  AsmaName(40, 'الحسيب', 'Al-Hasiyb', 'Hisob-kitob qiluvchi, yetarli'),
  AsmaName(41, 'الجليل', 'Al-Jaliyl', 'Ulug\'lik va azamat egasi'),
  AsmaName(42, 'الكريم', 'Al-Kariym', 'Karami, saxovati cheksiz'),
  AsmaName(43, 'الرقيب', 'Ar-Raqiyb', 'Kuzatib turuvchi'),
  AsmaName(44, 'المجيب', 'Al-Mujiyb', 'Duolarni ijobat qiluvchi'),
  AsmaName(45, 'الواسع', 'Al-Vosi\'', 'Rahmati va ilmi keng'),
  AsmaName(46, 'الحكيم', 'Al-Hakiym', 'Hikmat egasi'),
  AsmaName(47, 'الودود', 'Al-Vadud', 'Bandalarini sevuvchi'),
  AsmaName(48, 'المجيد', 'Al-Majiyd', 'Shon-shuhrat egasi'),
  AsmaName(49, 'الباعث', 'Al-Ba\'is', 'Qayta tiriltiruvchi'),
  AsmaName(50, 'الشهيد', 'Ash-Shahiyd', 'Har narsaga guvoh'),
  AsmaName(51, 'الحق', 'Al-Haqq', 'Haqiqat, borligi shubhasiz'),
  AsmaName(52, 'الوكيل', 'Al-Vakiyl', 'Ishonch bilan topshiriladigan vakil'),
  AsmaName(53, 'القوي', 'Al-Qaviyy', 'Cheksiz kuch egasi'),
  AsmaName(54, 'المتين', 'Al-Matiyn', 'Mustahkam, mahkam'),
  AsmaName(55, 'الولي', 'Al-Valiyy', 'Do\'st, madadkor'),
  AsmaName(56, 'الحميد', 'Al-Hamiyd', 'Barcha maqtovga loyiq'),
  AsmaName(57, 'المحصي', 'Al-Muhsiy', 'Hamma narsani sanab, hisoblab turuvchi'),
  AsmaName(58, 'المبدئ', 'Al-Mubdi\'', 'Yo\'qdan ilk bor yaratuvchi'),
  AsmaName(59, 'المعيد', 'Al-Mu\'iyd', 'Qayta yaratuvchi'),
  AsmaName(60, 'المحيي', 'Al-Muhyiy', 'Hayot beruvchi'),
  AsmaName(61, 'المميت', 'Al-Mumiyt', 'O\'lim beruvchi'),
  AsmaName(62, 'الحي', 'Al-Hayy', 'Abadiy tirik'),
  AsmaName(63, 'القيوم', 'Al-Qayyum', 'O\'zi qoim, borliqni tutib turuvchi'),
  AsmaName(64, 'الواجد', 'Al-Vojid', 'Hech narsaga muhtoj bo\'lmaydigan'),
  AsmaName(65, 'الماجد', 'Al-Mojid', 'Shon-shavkati ulug\''),
  AsmaName(66, 'الواحد', 'Al-Vohid', 'Yagona, birgina'),
  AsmaName(67, 'الأحد', 'Al-Ahad', 'Tengsiz yakka-yagona'),
  AsmaName(68, 'الصمد', 'As-Samad', 'Hamma muhtoj, O\'zi beniyoz'),
  AsmaName(69, 'القادر', 'Al-Qodir', 'Har narsaga qodir'),
  AsmaName(70, 'المقتدر', 'Al-Muqtadir', 'Cheksiz qudrat sohibi'),
  AsmaName(71, 'المقدم', 'Al-Muqaddim', 'Oldinga suruvchi'),
  AsmaName(72, 'المؤخر', 'Al-Mu\'axxir', 'Keyinga qoldiruvchi'),
  AsmaName(73, 'الأول', 'Al-Avval', 'Boshlanishi yo\'q, Avvalgi'),
  AsmaName(74, 'الآخر', 'Al-Oxir', 'Oxiri yo\'q, Oxirgi'),
  AsmaName(75, 'الظاهر', 'Az-Zohir', 'Oshkora, borligi ayon'),
  AsmaName(76, 'الباطن', 'Al-Botin', 'Yashirin, aql yetmas'),
  AsmaName(77, 'الوالي', 'Al-Voliy', 'Barchani boshqaruvchi'),
  AsmaName(78, 'المتعالي', 'Al-Muta\'oliy', 'Har nuqsondan yuksak'),
  AsmaName(79, 'البر', 'Al-Barr', 'Yaxshilik, ehson egasi'),
  AsmaName(80, 'التواب', 'At-Tavvob', 'Tavbalarni qabul qiluvchi'),
  AsmaName(81, 'المنتقم', 'Al-Muntaqim', 'Gunohkorlardan intiqom oluvchi'),
  AsmaName(82, 'العفو', 'Al-Afuvv', 'Gunohlarni o\'chiruvchi, avf etuvchi'),
  AsmaName(83, 'الرؤوف', 'Ar-Ra\'uf', 'Juda mehribon, shafqatli'),
  AsmaName(84, 'مالك الملك', 'Molik-ul-Mulk', 'Butun mulk egasi'),
  AsmaName(85, 'ذو الجلال والإكرام', 'Zul-Jaloli val-Ikrom',
      'Ulug\'lik va karam egasi'),
  AsmaName(86, 'المقسط', 'Al-Muqsit', 'Adolat bilan hukm qiluvchi'),
  AsmaName(87, 'الجامع', 'Al-Jomi\'', 'Yig\'uvchi, jamlaydigan'),
  AsmaName(88, 'الغني', 'Al-G\'aniyy', 'Beniyoz, boy'),
  AsmaName(89, 'المغني', 'Al-Mug\'niy', 'Boy qiluvchi, muhtojlikdan qutqaruvchi'),
  AsmaName(90, 'المانع', 'Al-Moni\'', 'To\'suvchi, man qiluvchi'),
  AsmaName(91, 'الضار', 'Az-Zorr', 'Hikmat bilan ziyon yetkazuvchi'),
  AsmaName(92, 'النافع', 'An-Nofi\'', 'Foyda yetkazuvchi'),
  AsmaName(93, 'النور', 'An-Nur', 'Nur, olamlarni yorituvchi'),
  AsmaName(94, 'الهادي', 'Al-Hodiy', 'Hidoyatga boshlovchi'),
  AsmaName(95, 'البديع', 'Al-Badiy\'', 'Misli yo\'q go\'zal yaratuvchi'),
  AsmaName(96, 'الباقي', 'Al-Boqiy', 'Abadiy, boqiy qoluvchi'),
  AsmaName(97, 'الوارث', 'Al-Voris', 'Hamma narsa qaytadigan Voris'),
  AsmaName(98, 'الرشيد', 'Ar-Rashiyd', 'To\'g\'ri yo\'lga boshlovchi'),
  AsmaName(99, 'الصبور', 'As-Sabur', 'Cheksiz sabrli'),
];
